#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
aggregate_multiseed.py — 把 save/ 下 4 类实验聚合：
  - main_3seed_*           主对比表（6 方法 × 3 seed × 100 ep）
  - ablation_3seed_*       消融表（4 变体 × 3 seed × 100 ep）
  - sens_V*                V 敏感性（5 个 V × 1 seed）
  - sens_dp_sigma*         σ_dp 敏感性（7 个 σ × 1 seed）

输出：
  - stdout 的对照表
  - save/agg_main_table.tex / agg_ablation_table.tex / agg_sens_dp_table.tex 等
    可直接 \\input 到论文里
  - save/agg_summary.json 给后续画图脚本读
"""
import argparse
import json
import pickle
from pathlib import Path
from collections import defaultdict
import numpy as np

ROOT = Path(__file__).parent.parent
SAVE = ROOT / 'save'

MAIN_TAGS = [
    ('hybrid_SV_Energy_Lyapunov_LDP', 'Ours'),
    ('random_LDP',                     'FedAvg'),
    ('random_FedProx_LDP',             'FedProx'),
    ('poc_LDP',                        'PoC'),
    ('fedcs_Energy_LDP',               'FedCS'),
]

ABL_TAGS = [
    ('hybrid_SV_Energy_Lyapunov_LDP', 'Full (SV + Lyap + Energy)'),
    ('random_Energy_Lyapunov_LDP',     'w/o SV'),
    ('hybrid_SV_Energy_LDP',           'w/o Lyap'),
    ('hybrid_SV_LDP',                  'w/o Energy'),
]


def find_tag(name):
    s = Path(name).stem
    m = '_B[32]_'
    i = s.find(m)
    return s[i + len(m):] if i >= 0 else None


def load_acc(path):
    with open(path, 'rb') as f:
        d = pickle.load(f)
    a = np.asarray(d['test_accuracy'], dtype=np.float64)
    return (a * 100.0 if a.max() <= 1.5 else a), d


def stat_block(arrs):
    """list[np.ndarray] -> dict of summary numbers (mean±std on last5/final)"""
    finals = np.array([a[-1] for a in arrs])
    last5  = np.array([a[-5:].mean() for a in arrs])
    slopes = np.array([np.polyfit(np.arange(20), a[-20:], 1)[0] for a in arrs])
    return dict(
        n=len(arrs),
        final_mean=float(finals.mean()), final_std=float(finals.std(ddof=0)),
        last5_mean=float(last5.mean()),  last5_std=float(last5.std(ddof=0)),
        slope_mean=float(slopes.mean()),
    )


# ---------------- main ----------------

def aggregate_main(tag_filter=None):
    data = defaultdict(list)
    folders = sorted(SAVE.glob('main_3seed_a0.1_sigma0.01_seed*'))
    if tag_filter:
        folders = [f for f in folders if tag_filter in f.name]
    for folder in folders:
        for pkl in folder.glob('*.pkl'):
            t = find_tag(pkl.name)
            if t is None:
                continue
            acc, _ = load_acc(pkl)
            data[t].append(acc)
    return data, folders


def aggregate_ablation(tag_filter=None):
    data = defaultdict(list)
    folders = sorted(SAVE.glob('ablation_3seed_a0.1_seed*'))
    if tag_filter:
        folders = [f for f in folders if tag_filter in f.name]
    for folder in folders:
        for pkl in folder.glob('*.pkl'):
            t = find_tag(pkl.name)
            if t is None:
                continue
            acc, _ = load_acc(pkl)
            data[t].append(acc)
    return data, folders


def aggregate_sens_V():
    out = {}
    for v in [1, 5, 10, 20, 50]:
        folders = sorted(SAVE.glob(f'sens_V{v}_*'))
        if not folders:
            continue
        pkls = list(folders[-1].glob('*.pkl'))
        if pkls:
            out[v] = load_acc(pkls[0])[0]
    return out


def aggregate_sens_dp():
    out = {}
    for s in [0.0, 0.01, 0.05, 0.1, 0.2, 0.5, 1.0]:
        folders = sorted(SAVE.glob(f'sens_dp_sigma{s}_*'))
        if not folders:
            continue
        pkls = list(folders[-1].glob('*.pkl'))
        if pkls:
            out[s] = load_acc(pkls[0])[0]
    return out


# ---------------- LaTeX writers ----------------

def write_main_table_tex(data, path: Path):
    rows = []
    summaries = {label: stat_block(data[tag]) for tag, label in MAIN_TAGS if tag in data}
    if not summaries:
        return
    best = max(summaries, key=lambda k: summaries[k]['last5_mean'])
    for tag, label in MAIN_TAGS:
        st = summaries.get(label)
        if st is None:
            rows.append(f'{label} & N/A & N/A \\\\')
            continue
        cell5 = f"{st['last5_mean']:.2f} $\\pm$ {st['last5_std']:.2f}"
        cellf = f"{st['final_mean']:.2f} $\\pm$ {st['final_std']:.2f}"
        if label == best:
            cell5 = '\\textbf{' + cell5 + '}'
        rows.append(f'{label} & {cell5} & {cellf} \\\\')
    body = '\n'.join(rows)
    text = ("% Generated by aggregate_multiseed.py\n"
            "% CIFAR-10, alpha=0.1, sigma_dp=0.01, 100 epochs, 3 seeds (42/123/2024).\n"
            "% Columns: last-5-round avg accuracy, final-round accuracy. mean +/- std.\n"
            + body + '\n')
    path.write_text(text, encoding='utf-8')


def write_ablation_table_tex(data, path: Path):
    rows = []
    summaries = {label: stat_block(data[tag]) for tag, label in ABL_TAGS if tag in data}
    if not summaries:
        return
    best = max(summaries, key=lambda k: summaries[k]['last5_mean'])
    for tag, label in ABL_TAGS:
        st = summaries.get(label)
        if st is None:
            rows.append(f'{label} & N/A \\\\')
            continue
        cell5 = f"{st['last5_mean']:.2f} $\\pm$ {st['last5_std']:.2f}"
        if label == best:
            cell5 = '\\textbf{' + cell5 + '}'
        rows.append(f'{label} & {cell5} \\\\')
    text = ("% Generated by aggregate_multiseed.py\n"
            "% CIFAR-10, alpha=0.1, 100 epochs, 3 seeds. Last-5 mean +/- std.\n"
            + '\n'.join(rows) + '\n')
    path.write_text(text, encoding='utf-8')


def write_sens_dp_table_tex(data, path: Path):
    rows = []
    for s in sorted(data.keys()):
        acc = data[s]
        last5 = acc[-5:].mean()
        final = acc[-1]
        rows.append(f'{s:.2f} & {last5:.2f} & {final:.2f} \\\\')
    text = ("% Generated by aggregate_multiseed.py\n"
            "% sigma_dp sweep, alpha=0.1, V=10, 100 epochs, single seed=42.\n"
            "% Columns: sigma_dp, last-5 acc (%), final acc (%).\n"
            + '\n'.join(rows) + '\n')
    path.write_text(text, encoding='utf-8')


def write_sens_V_table_tex(data, path: Path):
    rows = []
    for v in sorted(data.keys()):
        acc = data[v]
        last5 = acc[-5:].mean()
        final = acc[-1]
        rows.append(f'{v} & {last5:.2f} & {final:.2f} \\\\')
    text = ("% Generated by aggregate_multiseed.py\n"
            "% V sweep, alpha=0.1, sigma_dp=0.01, 100 epochs, single seed=42.\n"
            "% Columns: V, last-5 acc (%), final acc (%).\n"
            + '\n'.join(rows) + '\n')
    path.write_text(text, encoding='utf-8')


# ---------------- main ----------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--tag', default=None)
    args = parser.parse_args()

    print('=' * 80)
    print('MAIN — α=0.1, σ_dp=0.01, 100 ep, 3 seeds')
    print('=' * 80)
    main_data, main_folders = aggregate_main(args.tag)
    for f in main_folders:
        print(f'  found: {f.name}')
    summary_main = {}
    for tag, label in MAIN_TAGS:
        if tag not in main_data:
            print(f'  {label:10s}: missing')
            continue
        st = stat_block(main_data[tag])
        summary_main[label] = st
        print(f'  {label:10s}: last5 {st["last5_mean"]:5.2f}±{st["last5_std"]:4.2f}  '
              f'final {st["final_mean"]:5.2f}±{st["final_std"]:4.2f}  '
              f'slope {st["slope_mean"]:+.3f}')
    write_main_table_tex(main_data, SAVE / 'agg_main_table.tex')

    print('\n' + '=' * 80)
    print('ABLATION — α=0.1, 100 ep, 3 seeds')
    print('=' * 80)
    abl_data, abl_folders = aggregate_ablation(args.tag)
    for f in abl_folders:
        print(f'  found: {f.name}')
    summary_abl = {}
    for tag, label in ABL_TAGS:
        if tag not in abl_data:
            print(f'  {label:25s}: missing')
            continue
        st = stat_block(abl_data[tag])
        summary_abl[label] = st
        print(f'  {label:25s}: last5 {st["last5_mean"]:5.2f}±{st["last5_std"]:4.2f}')
    write_ablation_table_tex(abl_data, SAVE / 'agg_ablation_table.tex')

    print('\n' + '=' * 80)
    print('V SENSITIVITY — α=0.1, σ_dp=0.01, 100 ep, single seed')
    print('=' * 80)
    v_data = aggregate_sens_V()
    summary_V = {}
    for v in sorted(v_data.keys()):
        acc = v_data[v]
        last5 = acc[-5:].mean()
        summary_V[v] = float(last5)
        print(f'  V={v:>2d}: last5 {last5:.2f}%, final {acc[-1]:.2f}%')
    write_sens_V_table_tex(v_data, SAVE / 'agg_sens_V_table.tex')

    print('\n' + '=' * 80)
    print('σ_dp SENSITIVITY — α=0.1, V=10, 100 ep, single seed')
    print('=' * 80)
    s_data = aggregate_sens_dp()
    summary_dp = {}
    for s in sorted(s_data.keys()):
        acc = s_data[s]
        last5 = acc[-5:].mean()
        summary_dp[s] = float(last5)
        print(f'  σ={s:>5.2f}: last5 {last5:.2f}%, final {acc[-1]:.2f}%')
    write_sens_dp_table_tex(s_data, SAVE / 'agg_sens_dp_table.tex')

    summary = {
        'main': summary_main,
        'ablation': summary_abl,
        'sens_V': summary_V,
        'sens_dp': summary_dp,
    }
    (SAVE / 'agg_summary.json').write_text(json.dumps(summary, indent=2), encoding='utf-8')
    print(f'\nWritten: agg_main_table.tex, agg_ablation_table.tex, agg_sens_V_table.tex, '
          f'agg_sens_dp_table.tex, agg_summary.json (under save/)')


if __name__ == '__main__':
    main()
