#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Aggregate current channel-only experiment outputs under save/.

Expected folder layout:
  save/main/<run_tag>/seed*
  save/ablation/<run_tag>/seed*

The script writes compact LaTeX rows to:
  save/agg_main_table.tex
  save/agg_ablation_table.tex
  save/agg_summary.json
"""

import argparse
import json
import pickle
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).parent.parent
SAVE = ROOT / "save"

MAIN_TAGS = [
    ("hybrid_SV_Energy_Lyapunov_CDP", "Ours"),
    ("random_CDP", "FedAvg"),
    ("random_FedProx_CDP", "FedProx"),
    ("poc_CDP", "PoC"),
    ("oort_Energy_CDP", "Oort"),
    ("gca_Energy_CDP", "GCA"),
]

ABLATION_TAGS = [
    ("hybrid_SV_Energy_Lyapunov_CDP", "Full (SV + Lyap + Energy)"),
    ("random_Energy_Lyapunov_CDP", "w/o SV"),
    ("hybrid_SV_Energy_CDP", "w/o Lyap"),
    ("hybrid_SV_CDP", "w/o Energy"),
]


def find_tag(path):
    stem = Path(path).stem
    marker = "_B[32]_"
    idx = stem.find(marker)
    return stem[idx + len(marker):] if idx >= 0 else None


def load_accuracy(path):
    with open(path, "rb") as f:
        data = pickle.load(f)
    acc = np.asarray(data["test_accuracy"], dtype=np.float64)
    if acc.max() <= 1.5:
        acc = acc * 100.0
    return acc


def stat_block(series):
    finals = np.asarray([acc[-1] for acc in series], dtype=np.float64)
    last5 = np.asarray([acc[-5:].mean() for acc in series], dtype=np.float64)
    return {
        "n": int(len(series)),
        "final_mean": float(finals.mean()),
        "final_std": float(finals.std(ddof=0)),
        "last5_mean": float(last5.mean()),
        "last5_std": float(last5.std(ddof=0)),
    }


def collect_group(group, tag=None):
    base = SAVE / group
    if not base.exists():
        return defaultdict(list), []
    run_dirs = sorted([p for p in base.iterdir() if p.is_dir()])
    if tag:
        run_dirs = [p for p in run_dirs if tag in p.name]
    if not run_dirs:
        return defaultdict(list), []
    selected_runs = [run_dirs[-1]]
    data = defaultdict(list)
    folders = []
    for run_dir in selected_runs:
        for folder in sorted(run_dir.glob("*")):
            if not folder.is_dir():
                continue
            folders.append(folder)
            for pkl in folder.glob("*.pkl"):
                method = find_tag(pkl)
                if method:
                    data[method].append(load_accuracy(pkl))
    return data, folders


def write_rows(data, tags, path, include_final=True):
    summaries = {label: stat_block(data[tag]) for tag, label in tags if tag in data}
    if not summaries:
        return {}
    best = max(summaries, key=lambda label: summaries[label]["last5_mean"])
    rows = []
    for tag, label in tags:
        stats = summaries.get(label)
        if stats is None:
            rows.append(f"{label} & N/A" + (" & N/A" if include_final else "") + r" \\")
            continue
        last5 = f"{stats['last5_mean']:.2f} $\\pm$ {stats['last5_std']:.2f}"
        final = f"{stats['final_mean']:.2f} $\\pm$ {stats['final_std']:.2f}"
        if label == best:
            last5 = "\\textbf{" + last5 + "}"
        rows.append(f"{label} & {last5}" + (f" & {final}" if include_final else "") + r" \\")
    path.write_text("% Generated by aggregate_multiseed.py\n" + "\n".join(rows) + "\n", encoding="utf-8")
    return summaries


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag", default=None, help="Optional run tag under save/main or save/ablation")
    args = parser.parse_args()

    main_data, main_folders = collect_group("main", args.tag)
    ablation_data, ablation_folders = collect_group("ablation", args.tag)

    print("MAIN folders:")
    for folder in main_folders:
        print(f"  {folder.relative_to(SAVE)}")
    main_summary = write_rows(main_data, MAIN_TAGS, SAVE / "agg_main_table.tex", include_final=True)

    print("\nABLATION folders:")
    for folder in ablation_folders:
        print(f"  {folder.relative_to(SAVE)}")
    ablation_summary = write_rows(ablation_data, ABLATION_TAGS, SAVE / "agg_ablation_table.tex", include_final=False)

    summary = {"main": main_summary, "ablation": ablation_summary}
    (SAVE / "agg_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("\nWritten: save/agg_main_table.tex, save/agg_ablation_table.tex, save/agg_summary.json")


if __name__ == "__main__":
    main()
