#!/usr/bin/env python
"""Paired significance analysis for the CIFAR-10 main comparison."""

import argparse
import csv
import itertools
import json
import pickle
from pathlib import Path

import numpy as np
from scipy import stats


METHOD_TAGS = {
    "ours": "hybrid_SV_Energy_Lyapunov_CDP",
    "fedavg": "random_CDP",
    "fedprox": "random_FedProx_CDP",
    "oort": "oort_Energy_CDP",
    "gca": "gca_Energy_CDP",
    "fedmsv": "fedmsv_CDP",
}
BASELINES = ["fedavg", "fedprox", "oort", "gca", "fedmsv"]


def normalize_accuracy(values):
    result = np.asarray(values, dtype=np.float64)
    if result.size and np.nanmax(result) <= 1.5:
        result = result * 100.0
    return result


def load_result(path):
    with Path(path).open("rb") as handle:
        data = pickle.load(handle)
    args = data.get("args", {}) or {}
    accuracy = normalize_accuracy(data.get("test_accuracy", []))
    if not accuracy.size:
        raise ValueError("No test_accuracy values in {}".format(path))
    return {
        "seed": int(args.get("seed", -1)),
        "last5": float(accuracy[-min(5, accuracy.size):].mean()),
        "final": float(accuracy[-1]),
        "path": str(path),
    }


def collect_method(root, method):
    root = Path(root)
    if not root.exists():
        return {}
    tag = METHOD_TAGS[method]
    records = {}
    for path in sorted(root.rglob("*.pkl")):
        if tag not in path.stem:
            continue
        record = load_result(path)
        if record["seed"] >= 0:
            records[record["seed"]] = record
    return records


def exact_sign_flip_pvalue(differences):
    differences = np.asarray(differences, dtype=np.float64)
    observed = abs(float(differences.mean()))
    exceedances = 0
    total = 0
    for signs in itertools.product((-1.0, 1.0), repeat=len(differences)):
        statistic = abs(float(np.mean(differences * np.asarray(signs))))
        exceedances += int(statistic >= observed - 1e-12)
        total += 1
    return float(exceedances) / float(total)


def holm_adjust(p_values):
    finite_indices = [
        index for index, value in enumerate(p_values) if np.isfinite(value)
    ]
    count = len(finite_indices)
    order = sorted(finite_indices, key=lambda index: p_values[index])
    adjusted = [float("nan")] * len(p_values)
    running = 0.0
    for rank, index in enumerate(order):
        value = min(1.0, (count - rank) * p_values[index])
        running = max(running, value)
        adjusted[index] = running
    return adjusted


def confidence_interval(differences, confidence=0.95):
    differences = np.asarray(differences, dtype=np.float64)
    mean = float(differences.mean())
    if differences.size < 2:
        return mean, mean
    standard_error = float(stats.sem(differences))
    critical = float(stats.t.ppf((1.0 + confidence) / 2.0, differences.size - 1))
    return mean - critical * standard_error, mean + critical * standard_error


def paired_statistics(ours, baseline, metric):
    seeds = sorted(set(ours).intersection(baseline))
    ours_values = np.asarray([ours[seed][metric] for seed in seeds], dtype=np.float64)
    baseline_values = np.asarray([baseline[seed][metric] for seed in seeds], dtype=np.float64)
    differences = ours_values - baseline_values
    mean_difference = float(differences.mean()) if differences.size else float("nan")
    std_difference = float(differences.std(ddof=1)) if differences.size > 1 else float("nan")
    effect_size = (
        mean_difference / std_difference
        if differences.size > 1 and std_difference > 0.0
        else float("nan")
    )
    ci_low, ci_high = confidence_interval(differences) if differences.size else (float("nan"), float("nan"))
    p_value = exact_sign_flip_pvalue(differences) if differences.size else float("nan")
    return {
        "metric": metric,
        "n_pairs": int(differences.size),
        "seeds": seeds,
        "ours_mean": float(ours_values.mean()) if ours_values.size else float("nan"),
        "baseline_mean": float(baseline_values.mean()) if baseline_values.size else float("nan"),
        "mean_difference": mean_difference,
        "ci95_low": ci_low,
        "ci95_high": ci_high,
        "cohen_dz": effect_size,
        "p_raw": p_value,
    }


def write_csv(path, rows):
    fields = [
        "metric", "comparison", "n_pairs", "seeds", "ours_mean",
        "baseline_mean", "mean_difference", "ci95_low", "ci95_high",
        "cohen_dz", "p_raw", "p_holm", "significant_0_05",
    ]
    with Path(path).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_latex(path, rows):
    lines = ["% Generated by analyze_significance.py"]
    for row in rows:
        if row["metric"] != "last5":
            continue
        lines.append(
            "{comparison} & {mean_difference:.2f} & [{ci95_low:.2f}, {ci95_high:.2f}] & "
            "{p_holm:.4f} & {cohen_dz:.2f} \\\\".format(**row)
        )
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--new-root", required=True)
    parser.add_argument("--existing", action="append", default=[], help="method=path")
    parser.add_argument("--output", required=True)
    parser.add_argument(
        "--expected-pairs",
        type=int,
        default=10,
        help="required paired seeds per comparison; use 0 for exploratory analysis",
    )
    args = parser.parse_args()

    records = {method: collect_method(Path(args.new_root) / method, method) for method in METHOD_TAGS}
    for specification in args.existing:
        method, path = specification.split("=", 1)
        if method not in METHOD_TAGS:
            raise ValueError("Unknown method in --existing: {}".format(method))
        existing = collect_method(path, method)
        for seed, record in existing.items():
            records[method].setdefault(seed, record)

    if args.expected_pairs < 0:
        raise ValueError("--expected-pairs must be non-negative")
    if args.expected_pairs:
        incomplete = []
        for baseline in BASELINES:
            paired_seeds = sorted(set(records["ours"]).intersection(records[baseline]))
            if len(paired_seeds) != args.expected_pairs:
                incomplete.append(
                    "{}: {} paired seeds {}".format(
                        baseline, len(paired_seeds), paired_seeds
                    )
                )
        if incomplete:
            raise RuntimeError(
                "Significance analysis requires exactly {} paired seeds per "
                "comparison. Incomplete comparisons: {}".format(
                    args.expected_pairs, "; ".join(incomplete)
                )
            )

    rows = []
    for metric in ("last5", "final"):
        metric_rows = []
        for baseline in BASELINES:
            row = paired_statistics(records["ours"], records[baseline], metric)
            row["comparison"] = "Ours vs {}".format(baseline)
            metric_rows.append(row)
        adjusted = holm_adjust([row["p_raw"] for row in metric_rows])
        for row, p_holm in zip(metric_rows, adjusted):
            row["p_holm"] = p_holm
            row["significant_0_05"] = bool(np.isfinite(p_holm) and p_holm < 0.05)
            row["seeds"] = "[{}]".format(",".join(str(seed) for seed in row["seeds"]))
            rows.append(row)

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    write_csv(output / "significance_results.csv", rows)
    write_latex(output / "significance_table.tex", rows)
    payload = {
        "methods": {
            method: sorted(records[method]) for method in records
        },
        "tests": rows,
        "test": "exact paired sign-flip permutation test",
        "multiple_comparison_correction": "Holm",
    }
    (output / "significance_results.json").write_text(
        json.dumps(payload, indent=2, allow_nan=True), encoding="utf-8"
    )

    print("Written: {}".format(output))
    for row in rows:
        print(
            "{metric}: {comparison}, n={n_pairs}, diff={mean_difference:.3f}, "
            "p_holm={p_holm:.4f}".format(**row)
        )


if __name__ == "__main__":
    main()
