#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate the Dirichlet-alpha sensitivity figure and LaTeX table."""
import json
import pickle
from pathlib import Path
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).parent.parent
SAVE = ROOT / "save"
FIG_OUT = ROOT / "latex" / "figures" / "sensitivity_alpha.pdf"
PNG_OUT = SAVE / "sensitivity_alpha.png"
TEX_OUT = SAVE / "agg_sens_alpha_table.tex"
JSON_OUT = SAVE / "agg_sens_alpha.json"

ALPHAS = [0.1, 0.25, 0.5, 1.0]
METHODS = [
    ("hybrid_SV_Energy_Lyapunov_CDP", "Ours", "C0", "-"),
    ("random_CDP", "FedAvg", "C1", "--"),
    ("random_FedProx_CDP", "FedProx", "C2", "-."),
    ("poc_CDP", "PoC", "C3", ":"),
    ("oort_Energy_CDP", "Oort", "C4", (0, (3, 1, 1, 1))),
]


def find_tag(name: str):
    stem = Path(name).stem
    marker = "_B[32]_"
    idx = stem.find(marker)
    return stem[idx + len(marker):] if idx >= 0 else None


def normalize(acc):
    arr = np.asarray(acc, dtype=np.float64)
    return arr * 100.0 if arr.max() <= 1.5 else arr


def load_acc(path: Path):
    with open(path, "rb") as f:
        data = pickle.load(f)
    return normalize(data["test_accuracy"])


def load_alpha_runs(tag=None):
    curves = defaultdict(dict)
    root = SAVE / "sensitivity_alpha"
    if tag:
        run_dir = root / tag
    else:
        runs = sorted([p for p in root.iterdir() if p.is_dir()])
        if not runs:
            raise FileNotFoundError("No run directories found under save/sensitivity_alpha")
        run_dir = runs[-1]
    print(f"using {run_dir}")

    for alpha in ALPHAS:
        folder = run_dir / f"alpha{alpha}"
        if not folder.exists():
            folder = run_dir / f"alpha{alpha:.1f}"
        if not folder.exists():
            folder = run_dir / f"alpha{alpha:.2f}"
        if not folder.exists():
            print(f"missing folder for alpha={alpha}: {folder}")
            continue
        for pkl in folder.glob("*.pkl"):
            method_tag = find_tag(pkl.name)
            if method_tag:
                curves[alpha][method_tag] = load_acc(pkl)

    return curves


def write_table(curves):
    rows = []
    for alpha in ALPHAS:
        row = [f"{alpha:.2f}"]
        for tag, _, _, _ in METHODS:
            acc = curves.get(alpha, {}).get(tag)
            row.append("N/A" if acc is None else f"{acc[-5:].mean():.2f}")
        rows.append(" & ".join(row) + r" \\")

    text = (
        "% Generated by plot_sensitivity_alpha.py\n"
        "% CIFAR-10, channel-only privacy, K=5, gamma_ch=0.1, V=10, T=100, single seed=42.\n"
        "% Columns: alpha, Ours last-5 acc, FedAvg last-5 acc, FedProx last-5 acc, PoC last-5 acc, Oort last-5 acc.\n"
        + "\n".join(rows)
        + "\n"
    )
    TEX_OUT.write_text(text, encoding="utf-8")


def plot(curves):
    fig, ax = plt.subplots(figsize=(6.4, 4.2))
    for tag, label, color, linestyle in METHODS:
        xs, ys = [], []
        for alpha in ALPHAS:
            acc = curves.get(alpha, {}).get(tag)
            if acc is None:
                continue
            xs.append(alpha)
            ys.append(acc[-5:].mean())
        if xs:
            ax.plot(xs, ys, marker="o", label=label, color=color,
                    linestyle=linestyle, linewidth=1.8)

    ax.set_xscale("log")
    ax.set_xticks(ALPHAS)
    ax.set_xticklabels([str(a) for a in ALPHAS])
    ax.set_xlabel(r"Dirichlet concentration $\alpha$")
    ax.set_ylabel("Last-5 test accuracy (%)")
    ax.set_title("Sensitivity to non-IID level")
    ax.grid(alpha=0.3, linestyle=":")
    ax.legend(loc="lower right", fontsize=9)
    fig.tight_layout()
    FIG_OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG_OUT, bbox_inches="tight")
    fig.savefig(PNG_OUT, dpi=140, bbox_inches="tight")


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag", default=None, help="Run tag under save/sensitivity_alpha. Defaults to latest.")
    args = parser.parse_args()

    curves = load_alpha_runs(args.tag)
    summary = {}
    for alpha in ALPHAS:
        summary[str(alpha)] = {}
        for tag, label, _, _ in METHODS:
            acc = curves.get(alpha, {}).get(tag)
            if acc is not None:
                summary[str(alpha)][label] = {
                    "last5": float(acc[-5:].mean()),
                    "final": float(acc[-1]),
                }

    write_table(curves)
    plot(curves)
    JSON_OUT.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"wrote {FIG_OUT}")
    print(f"wrote {PNG_OUT}")
    print(f"wrote {TEX_OUT}")
    print(f"wrote {JSON_OUT}")
    missing = []
    for alpha in ALPHAS:
        for tag, label, _, _ in METHODS:
            if tag not in curves.get(alpha, {}):
                missing.append(f"alpha={alpha}, {label}")
    if missing:
        print("missing runs:")
        for item in missing:
            print(f"  - {item}")


if __name__ == "__main__":
    main()
