#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate the Dirichlet-alpha sensitivity figure and LaTeX table.

The sweep is single-seed. For alpha=0.1 we reuse the existing seed=42 main run;
for alpha in {0.25, 0.5, 1.0} we read folders produced by run_sensitivity_alpha.sh.
"""
import json
import pickle
from pathlib import Path
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).parent.parent
SAVE = ROOT / "save"
FIG_OUT = ROOT / "latex" / "figures" / "sensitivity_alpha.pdf"
PNG_OUT = SAVE / "sensitivity_alpha.png"
TEX_OUT = SAVE / "agg_sens_alpha_table.tex"
JSON_OUT = SAVE / "agg_sens_alpha.json"

ALPHAS = [0.1, 0.25, 0.5, 1.0]
METHODS = [
    ("hybrid_SV_Energy_Lyapunov_CDP", "Ours", "C0", "-"),
    ("random_CDP", "FedAvg", "C1", "--"),
    ("poc_CDP", "PoC", "C3", ":"),
]


def find_tag(name: str):
    stem = Path(name).stem
    marker = "_B[32]_"
    idx = stem.find(marker)
    return stem[idx + len(marker):] if idx >= 0 else None


def normalize(acc):
    arr = np.asarray(acc, dtype=np.float64)
    return arr * 100.0 if arr.max() <= 1.5 else arr


def load_acc(path: Path):
    with open(path, "rb") as f:
        data = pickle.load(f)
    return normalize(data["test_accuracy"])


def latest_folder(pattern: str):
    folders = sorted(SAVE.glob(pattern))
    return folders[-1] if folders else None


def load_alpha_runs():
    curves = defaultdict(dict)

    folder = latest_folder("main_3seed_a0.1_sigma0.01_seed42_*")
    if folder:
        for pkl in folder.glob("*.pkl"):
            tag = find_tag(pkl.name)
            if tag:
                curves[0.1][tag] = load_acc(pkl)

    for alpha in [0.25, 0.5, 1.0]:
        folder = latest_folder(f"sens_alpha{alpha}_seed42_*")
        if not folder:
            continue
        for pkl in folder.glob("*.pkl"):
            tag = find_tag(pkl.name)
            if tag:
                curves[alpha][tag] = load_acc(pkl)

    return curves


def write_table(curves):
    rows = []
    for alpha in ALPHAS:
        row = [f"{alpha:.2f}"]
        for tag, _, _, _ in METHODS:
            acc = curves.get(alpha, {}).get(tag)
            row.append("N/A" if acc is None else f"{acc[-5:].mean():.2f}")
        rows.append(" & ".join(row) + r" \\")

    text = (
        "% Generated by plot_sensitivity_alpha.py\n"
        "% CIFAR-10, q=0.05, sigma_dp=1.5, V=10, T=100, single seed=42.\n"
        "% Columns: alpha, Ours last-5 acc, FedAvg last-5 acc, PoC last-5 acc.\n"
        + "\n".join(rows)
        + "\n"
    )
    TEX_OUT.write_text(text, encoding="utf-8")


def plot(curves):
    fig, ax = plt.subplots(figsize=(6.4, 4.2))
    for tag, label, color, linestyle in METHODS:
        xs, ys = [], []
        for alpha in ALPHAS:
            acc = curves.get(alpha, {}).get(tag)
            if acc is None:
                continue
            xs.append(alpha)
            ys.append(acc[-5:].mean())
        if xs:
            ax.plot(xs, ys, marker="o", label=label, color=color,
                    linestyle=linestyle, linewidth=1.8)

    ax.set_xscale("log")
    ax.set_xticks(ALPHAS)
    ax.set_xticklabels([str(a) for a in ALPHAS])
    ax.set_xlabel(r"Dirichlet concentration $\alpha$")
    ax.set_ylabel("Last-5 test accuracy (%)")
    ax.set_title("Sensitivity to non-IID level")
    ax.grid(alpha=0.3, linestyle=":")
    ax.legend(loc="lower right", fontsize=9)
    fig.tight_layout()
    FIG_OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG_OUT, bbox_inches="tight")
    fig.savefig(PNG_OUT, dpi=140, bbox_inches="tight")


def main():
    curves = load_alpha_runs()
    summary = {}
    for alpha in ALPHAS:
        summary[str(alpha)] = {}
        for tag, label, _, _ in METHODS:
            acc = curves.get(alpha, {}).get(tag)
            if acc is not None:
                summary[str(alpha)][label] = {
                    "last5": float(acc[-5:].mean()),
                    "final": float(acc[-1]),
                }

    write_table(curves)
    plot(curves)
    JSON_OUT.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"wrote {FIG_OUT}")
    print(f"wrote {PNG_OUT}")
    print(f"wrote {TEX_OUT}")
    print(f"wrote {JSON_OUT}")
    missing = []
    for alpha in ALPHAS:
        for tag, label, _, _ in METHODS:
            if tag not in curves.get(alpha, {}):
                missing.append(f"alpha={alpha}, {label}")
    if missing:
        print("missing runs:")
        for item in missing:
            print(f"  - {item}")


if __name__ == "__main__":
    main()
