#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Summarize multi-seed Dirichlet-alpha sensitivity runs."""

import argparse
import csv
import json
import pickle
from collections import defaultdict
from pathlib import Path

import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parent.parent
SAVE = ROOT / "save"

ALPHAS = [0.1, 0.25, 0.5, 1.0]
METHODS = [
    ("hybrid_SV_Energy_Lyapunov_CDP", "Ours", "C0", "-"),
    ("random_CDP", "FedAvg", "C1", "--"),
    ("random_FedProx_CDP", "FedProx", "C2", "-."),
    ("poc_CDP", "PoC", "C3", ":"),
    ("oort_Energy_CDP", "Oort", "C5", "-."),
    ("gca_Energy_CDP", "GCA", "C4", (0, (3, 1, 1, 1))),
]


def method_from_filename(path):
    stem = Path(path).stem
    marker = "_B[32]_"
    idx = stem.find(marker)
    return stem[idx + len(marker):] if idx >= 0 else stem


def normalize_accuracy(values):
    arr = np.asarray(values, dtype=np.float64)
    if arr.size and np.nanmax(arr) <= 1.5:
        arr = arr * 100.0
    return arr


def load_record(path, alpha):
    with Path(path).open("rb") as f:
        data = pickle.load(f)
    args = data.get("args", {}) or {}
    acc = normalize_accuracy(data.get("test_accuracy", []))
    return {
        "alpha": float(alpha),
        "method_tag": method_from_filename(path),
        "seed": int(args.get("seed", -1)),
        "path": str(Path(path).relative_to(ROOT)),
        "last5_acc": float(acc[-min(5, len(acc)):].mean()) if acc.size else np.nan,
        "final_acc": float(acc[-1]) if acc.size else np.nan,
    }


def alpha_folder(run_root, alpha):
    candidates = [
        run_root / "alpha" / f"alpha{alpha}",
        run_root / "alpha" / f"alpha{alpha:.1f}",
        run_root / "alpha" / f"alpha{alpha:.2f}",
    ]
    for folder in candidates:
        if folder.exists():
            return folder
    return candidates[0]


def collect(run_root):
    rows = []
    for alpha in ALPHAS:
        folder = alpha_folder(run_root, alpha)
        if not folder.exists():
            continue
        for pkl in sorted(folder.glob("seed*/*/*.pkl")):
            rows.append(load_record(pkl, alpha))
        for pkl in sorted(folder.glob("seed*/*.pkl")):
            rows.append(load_record(pkl, alpha))
    return rows


def mean_std(values):
    arr = np.asarray(values, dtype=np.float64)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return np.nan, np.nan
    return float(arr.mean()), float(arr.std(ddof=0))


def fmt_pm(mean, std):
    if not np.isfinite(mean):
        return "N/A"
    return f"{mean:.2f} $\\pm$ {std:.2f}"


def summarize(rows):
    grouped = defaultdict(list)
    for row in rows:
        grouped[(row["alpha"], row["method_tag"])].append(row)

    summary = {}
    for alpha in ALPHAS:
        summary[alpha] = {}
        for tag, label, _, _ in METHODS:
            items = grouped.get((alpha, tag), [])
            last_m, last_s = mean_std([x["last5_acc"] for x in items])
            final_m, final_s = mean_std([x["final_acc"] for x in items])
            summary[alpha][label] = {
                "n": len(items),
                "last5_mean": last_m,
                "last5_std": last_s,
                "final_mean": final_m,
                "final_std": final_s,
                "seeds": sorted({x["seed"] for x in items if x["seed"] >= 0}),
            }
    return summary


def write_csv(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["alpha", "method_tag", "seed", "last5_acc", "final_acc", "path"]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_table(path, summary):
    lines = ["% Generated by summarize_sensitivity_multiseed.py"]
    header = "% Columns: alpha, " + ", ".join(label for _, label, _, _ in METHODS)
    lines.append(header)
    for alpha in ALPHAS:
        cells = [f"{alpha:.2f}"]
        for _, label, _, _ in METHODS:
            stats = summary[alpha][label]
            cells.append(fmt_pm(stats["last5_mean"], stats["last5_std"]))
        lines.append(" & ".join(cells) + r" \\")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def plot(path_pdf, path_png, summary):
    fig, ax = plt.subplots(figsize=(6.4, 4.2))
    for _, label, color, linestyle in METHODS:
        xs, ys = [], []
        for alpha in ALPHAS:
            val = summary[alpha][label]["last5_mean"]
            if np.isfinite(val):
                xs.append(alpha)
                ys.append(val)
        if xs:
            ax.plot(xs, ys, marker="o", label=label, color=color,
                    linestyle=linestyle, linewidth=1.8)
    ax.set_xscale("log")
    ax.set_xticks(ALPHAS)
    ax.set_xticklabels([str(a) for a in ALPHAS])
    ax.set_xlabel(r"Dirichlet concentration $\alpha$")
    ax.set_ylabel("Last-5 test accuracy (%)")
    ax.set_title("Sensitivity to non-IID level")
    ax.grid(alpha=0.3, linestyle=":")
    ax.legend(loc="lower right", fontsize=9, ncol=2, framealpha=0.85)
    fig.tight_layout()
    path_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path_pdf, bbox_inches="tight")
    fig.savefig(path_png, dpi=140, bbox_inches="tight")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag", default=None, help="Run tag under save/sensitivity_multiseed. Defaults to latest.")
    args = parser.parse_args()

    root = SAVE / "sensitivity_multiseed"
    if args.tag:
        run_root = root / args.tag
    else:
        runs = sorted([p for p in root.iterdir() if p.is_dir()])
        if not runs:
            raise FileNotFoundError("No run directories found under save/sensitivity_multiseed")
        run_root = runs[-1]
    if not run_root.exists():
        raise FileNotFoundError(f"Run directory not found: {run_root}")

    rows = collect(run_root)
    summary = summarize(rows)
    out = run_root / "summary_tables"
    write_csv(out / "alpha_runs.csv", rows)
    write_table(out / "alpha_table.tex", summary)
    (out / "alpha_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    plot(ROOT / "latex" / "figures" / "sensitivity_alpha.pdf",
         SAVE / "sensitivity_alpha.png", summary)

    print(f"Run root: {run_root.relative_to(ROOT)}")
    print(f"Records: {len(rows)}")
    print(f"Written: {out.relative_to(ROOT)}")
    missing = []
    for alpha in ALPHAS:
        for _, label, _, _ in METHODS:
            if summary[alpha][label]["n"] == 0:
                missing.append(f"alpha={alpha}, {label}")
    if missing:
        print("Missing runs:")
        for item in missing:
            print(f"  - {item}")


if __name__ == "__main__":
    main()
